version: '3.8'

services:
  chromadb:
    build: .
    volumes:
      - .:/app
      - chroma_data:/app/chroma_data
    ports:
      - "8000:8000"
    environment:
      - CHROMA_SERVER_HOST=0.0.0.0
      - CHROMA_SERVER_PORT=8000

volumes:
  chroma_data: 